In [1]:
import pandas as pd

#Ask Charmaine which paper these SNPs come from

h2_vars = pd.DataFrame(
    {
        "dbSNP" : ["rs12185268", "rs8070723", "rs1800547", "rs62063786", "rs62063787", "rs17651549", "rs10445337"], 
        "pos" : [45846317, 44081064, 44051846, 44061023, 44061036, 44061278, 44067400]
    }
)

h2_vars

dbSNP       pos
0  rs12185268  45846317
1   rs8070723  44081064
2   rs1800547  44051846
3  rs62063786  44061023
4  rs62063787  44061036
5  rs17651549  44061278
6  rs10445337  44067400

In [2]:

import gzip

with gzip.open('17.vcf.gz', 'rb') as vcf:
    for i in range(1,10):
        print(vcf.readline())

b'##fileformat=VCFv4.2\n'
b'##FILTER=<ID=PASS,Description="All filters passed">\n'
b'##contig=<ID=1,length=249250621>\n'
b'##contig=<ID=2,length=243199373>\n'
b'##contig=<ID=3,length=198022430>\n'
b'##contig=<ID=4,length=191154276>\n'
b'##contig=<ID=5,length=180915260>\n'
b'##contig=<ID=6,length=171115067>\n'
b'##contig=<ID=7,length=159138663>\n'


In [3]:
# import scikit-allel
import allel
# check which version is installed
print(allel.__version__)

1.2.1


In [4]:
# callset = allel.read_vcf('17.vcf.gz', region='17:43971748-44105700')

df_maptVars = allel.vcf_to_dataframe('17.vcf.gz', region='17:43971748-46000000', fields = "*")
df_maptVars

CHROM       POS           ID  REF ALT_1  ALT_2  ALT_3  QUAL  AC_1  AC_2  \
0        17  43971772            .    G     C    NaN    NaN   NaN     0    -1   
1        17  43971785            .    A     G    NaN    NaN   NaN   690    -1   
2        17  43971788            .    G     A    NaN    NaN   NaN     0    -1   
3        17  43971831            .    C     G    NaN    NaN   NaN     0    -1   
4        17  43971835            .    C     G    NaN    NaN   NaN     0    -1   
...     ...       ...          ...  ...   ...    ...    ...   ...   ...   ...   
45865    17  45999623  rs535805145    C     T    NaN    NaN   NaN     0    -1   
45866    17  45999724  rs184834526    T     C    NaN    NaN   NaN     0    -1   
45867    17  45999729  rs575754159    C     G    NaN    NaN   NaN     0    -1   
45868    17  45999890   rs56279716  CTT     C    NaN    NaN   NaN   316    -1   
45869    17  45999927  rs544668809    C     G    NaN    NaN   NaN     1    -1   

       ...  RefPanelAF_2  RefPanelAF_3  TYPED      INFO  FILTER_PASS  numalt  \
0      ...           NaN           NaN  False  1.000000         True       1   
1      ...           NaN           NaN  False  0.999913         True       1   
2      ...           NaN           NaN  False  0.040061         True       1   
3      ...           NaN           NaN  False  0.049698         True       1   
4      ...           NaN           NaN  False  1.000000         True       1   
...    ...           ...           ...    ...       ...          ...     ...   
45865  ...           NaN           NaN  False  0.049986         True       1   
45866  ...           NaN           NaN  False  0.239255         True       1   
45867  ...           NaN           NaN  False  0.049727         True       1   
45868  ...           NaN           NaN  False  0.988606         True       1   
45869  ...           NaN           NaN  False  0.749943         True       1   

       altlen_1  altlen_2  altlen_3  is_snp  
0             0         0         0    True  
1             0         0         0    True  
2             0         0         0    True  
3             0         0         0    True  
4             0         0         0    True  
...         ...       ...       ...     ...  
45865         0         0         0    True  
45866         0         0         0    True  
45867         0         0         0    True  
45868        -2         0         0   False  
45869         0         0         0    True  

[45870 rows x 23 columns]

In [5]:
df_maptVars[df_maptVars['ID'].str.contains('|'.join(h2_vars['dbSNP']))] #We do not see rs12185268 in our imputation data. This SNP resides within MAPT-AS1, not MAPT.
# df_maptVars[df_maptVars['POS'] == 45846317]

CHROM       POS          ID REF ALT_1  ALT_2  ALT_3  QUAL  AC_1  AC_2  \
2401    17  44051846   rs1800547   A     G    NaN    NaN   NaN    20    -1   
2691    17  44061023  rs62063786   G     A    NaN    NaN   NaN   181    -1   
2693    17  44061036  rs62063787   T     C    NaN    NaN   NaN   438    -1   
2700    17  44061278  rs17651549   C     T    NaN    NaN   NaN   438    -1   
2886    17  44067400  rs10445337   T     C    NaN    NaN   NaN   651    -1   
3338    17  44081064   rs8070723   A     G    NaN    NaN   NaN   671    -1   

      ...  RefPanelAF_2  RefPanelAF_3  TYPED      INFO  FILTER_PASS  numalt  \
2401  ...           NaN           NaN  False  0.116130         True       1   
2691  ...           NaN           NaN  False  0.513447         True       1   
2693  ...           NaN           NaN  False  0.546482         True       1   
2700  ...           NaN           NaN  False  0.548110         True       1   
2886  ...           NaN           NaN  False  0.805522         True       1   
3338  ...           NaN           NaN  False  0.756986         True       1   

      altlen_1  altlen_2  altlen_3  is_snp  
2401         0         0         0    True  
2691         0         0         0    True  
2693         0         0         0    True  
2700         0         0         0    True  
2886         0         0         0    True  
3338         0         0         0    True  

[6 rows x 23 columns]

In [6]:
df_maptVars[df_maptVars['ID'].str.contains('|'.join(h2_vars['dbSNP']))].index.tolist()

[2401, 2691, 2693, 2700, 2886, 3338]

In [7]:
vcf_17 = allel.read_vcf('17.vcf.gz', region='17:43971748-46000000', fields = "*")


In [8]:
vcf_17.keys()

dict_keys(['samples', 'calldata/ADS', 'calldata/DS', 'calldata/GP', 'calldata/GT', 'variants/AC', 'variants/ALT', 'variants/AN', 'variants/CHROM', 'variants/FILTER_PASS', 'variants/ID', 'variants/INFO', 'variants/POS', 'variants/QUAL', 'variants/REF', 'variants/RefPanelAF', 'variants/TYPED', 'variants/altlen', 'variants/is_snp', 'variants/numalt'])

In [9]:
for i in vcf_17['variants/ID']:
    if i == 'rs12185268':
        print('present')

In [10]:
vcf_17['calldata/GT'][0]


array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [11]:
gt_vcf_17 = allel.GenotypeArray(vcf_17['calldata/GT'])

In [12]:
gt_vcf_17.is_het().shape

(45870, 1654)

In [13]:
gt_array_hom_alt = gt_vcf_17.is_hom_alt()[df_maptVars[df_maptVars['ID'].str.contains('|'.join(h2_vars['dbSNP']))].index.tolist(),:]

gt_array_hom_alt

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [14]:
df_maptVars[df_maptVars['ID'].str.contains('|'.join(h2_vars['dbSNP']))]

CHROM       POS          ID REF ALT_1  ALT_2  ALT_3  QUAL  AC_1  AC_2  \
2401    17  44051846   rs1800547   A     G    NaN    NaN   NaN    20    -1   
2691    17  44061023  rs62063786   G     A    NaN    NaN   NaN   181    -1   
2693    17  44061036  rs62063787   T     C    NaN    NaN   NaN   438    -1   
2700    17  44061278  rs17651549   C     T    NaN    NaN   NaN   438    -1   
2886    17  44067400  rs10445337   T     C    NaN    NaN   NaN   651    -1   
3338    17  44081064   rs8070723   A     G    NaN    NaN   NaN   671    -1   

      ...  RefPanelAF_2  RefPanelAF_3  TYPED      INFO  FILTER_PASS  numalt  \
2401  ...           NaN           NaN  False  0.116130         True       1   
2691  ...           NaN           NaN  False  0.513447         True       1   
2693  ...           NaN           NaN  False  0.546482         True       1   
2700  ...           NaN           NaN  False  0.548110         True       1   
2886  ...           NaN           NaN  False  0.805522         True       1   
3338  ...           NaN           NaN  False  0.756986         True       1   

      altlen_1  altlen_2  altlen_3  is_snp  
2401         0         0         0    True  
2691         0         0         0    True  
2693         0         0         0    True  
2700         0         0         0    True  
2886         0         0         0    True  
3338         0         0         0    True  

[6 rows x 23 columns]

In [15]:
gt_array_hom_alt.shape

(6, 1654)

In [16]:
for i in range(0,6):
    print(gt_array_hom_alt[i,:].sum())

0
0
59
59
63
70


In [17]:

gt_array_hom_alt[:, 214]


array([False, False,  True,  True,  True,  True])

In [18]:
vcf_17["samples"].tolist().index("JR030")

214

In [19]:
h2_patients_hom_alt = pd.DataFrame(columns = vcf_17["samples"], 
                               data = gt_array_hom_alt,
                               index = df_maptVars[df_maptVars['ID'].str.contains('|'.join(h2_vars['dbSNP']))]['ID']
            )
             
h2_patients_hom_alt = h2_patients_hom_alt.reset_index()

h2_patients_hom_alt

ID  AH001  AH002  AH003  AH005  AH006  AH007  AH009  AH010  AH011  \
0   rs1800547  False  False  False  False  False  False  False  False  False   
1  rs62063786  False  False  False  False  False  False  False  False  False   
2  rs62063787  False  False  False  False  False  False  False  False  False   
3  rs17651549  False  False  False  False  False  False  False  False  False   
4  rs10445337  False  False  False  False  False  False  False  False  False   
5   rs8070723  False  False  False  False  False  False  False  False  False   

   ...  WP047  WP048  WP051  WP052  WP053  WP055  WP056  WP057  WP058  WP060  
0  ...  False  False  False  False  False  False  False  False  False  False  
1  ...  False  False  False  False  False  False  False  False  False  False  
2  ...  False  False  False  False  False  False  False  False  False  False  
3  ...  False  False  False  False  False  False  False  False  False  False  
4  ...  False  False  False  False  False  False  False  False  False  False  
5  ...  False  False  False  False  False  False  False  False  False  False  

[6 rows x 1655 columns]

In [20]:
h2_patients_hom_alt['JR030']

0    False
1    False
2     True
3     True
4     True
5     True
Name: JR030, dtype: bool

In [21]:
h2_patients_hom_alt.sum(axis=1)
    

0     0
1     0
2    59
3    59
4    63
5    70
dtype: int64

In [22]:
h2_patients_hom_alt_long = h2_patients_hom_alt.melt(id_vars=['ID'], 
                     value_vars = h2_patients_hom_alt.columns.difference(['ID']),
                    var_name='sample',
                    value_name='is_hom_alt')[['sample', 'ID', 'is_hom_alt']]

h2_patients_hom_alt_long

sample          ID  is_hom_alt
0     AH001   rs1800547       False
1     AH001  rs62063786       False
2     AH001  rs62063787       False
3     AH001  rs17651549       False
4     AH001  rs10445337       False
...     ...         ...         ...
9919  WP060  rs62063786       False
9920  WP060  rs62063787       False
9921  WP060  rs17651549       False
9922  WP060  rs10445337       False
9923  WP060   rs8070723       False

[9924 rows x 3 columns]

In [27]:
h2_patients_hom_alt_perSnp = h2_patients_hom_alt_long.groupby('ID')['is_hom_alt']

snp_stats = h2_patients_hom_alt_perSnp.sum() / (len(h2_patients_hom_alt_long['ID'])/6) * 100

snp_stats.to_csv("snp_stats.csv")
snp_stats

ID
rs10445337    3.808948
rs17651549    3.567110
rs1800547     0.000000
rs62063786    0.000000
rs62063787    3.567110
rs8070723     4.232164
Name: is_hom_alt, dtype: float64

In [25]:
len(h2_patients_hom_alt_long['ID'])/6

1654.0

In [330]:
h2_patients_hom_alt_snpCount = h2_patients_hom_alt_long.groupby('sample')['is_hom_alt'].sum()
h2_patients_hom_alt_snpCount

sample
AH001    0.0
AH002    0.0
AH003    0.0
AH005    0.0
AH006    0.0
        ... 
WP055    0.0
WP056    0.0
WP057    0.0
WP058    0.0
WP060    0.0
Name: is_hom_alt, Length: 1654, dtype: float64

In [331]:
h2_patients_hom_alt_snpCount.describe()

count    1654.000000
mean        0.151753
std         0.749636
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         4.000000
Name: is_hom_alt, dtype: float64

In [340]:
h2_patients_hom_alt_snpCount[h2_patients_hom_alt_snpCount >= 1]

sample
AH024    4.0
AH041    4.0
AH119    4.0
HH006    4.0
HH065    4.0
        ... 
RH146    4.0
RH168    4.0
RH180    1.0
RH183    1.0
SF011    4.0
Name: is_hom_alt, Length: 70, dtype: float64

In [341]:
h2_patients_hom_alt_snpCount[h2_patients_hom_alt_snpCount >= 1].to_csv("h2_patients_1plus.csv")

In [333]:
import numpy as np
import matplotlib.pyplot as plt
import datetime

%matplotlib inline

plt(gt_array_hom_alt[0])

TypeError: 'module' object is not callable

In [209]:
h2_patients_hom_alt[:,h2_patients_hom_alt.columns.intersection(lst)]

TypeError: '(slice(None, None, None), Index(['AH024', 'AH041', 'AH119', 'HH006', 'HH065', 'JR013', 'JR023', 'JR030',
       'JR033', 'JR048', 'JR114', 'JR127', 'JR130', 'JR153', 'JR181', 'JR212',
       'JR224', 'JR260', 'JR266', 'JR269', 'JR275', 'JR311', 'JR321', 'JR325',
       'JR350', 'JR372', 'JR397', 'JR463', 'MK038', 'MK046', 'MK053', 'MK061',
       'MK145', 'MK178', 'MK215', 'MK225', 'MK238', 'NH047', 'NH071', 'NH099',
       'NH127', 'NH133', 'NH136', 'NH172', 'OB058', 'OB179', 'PA015', 'PA027',
       'PA033', 'PA064', 'PA116', 'RH019', 'RH023', 'RH029', 'RH065', 'RH119',
       'RH146', 'RH168', 'SF011'],
      dtype='object'))' is an invalid key

In [208]:
lst = h2_patients_hom_alt_snpCount[h2_patients_hom_alt_snpCount >= 4].index.tolist()

h2_patients_hom_alt

Index(['AH024', 'AH041', 'AH119', 'HH006', 'HH065', 'JR013', 'JR023', 'JR030',
       'JR033', 'JR048', 'JR114', 'JR127', 'JR130', 'JR153', 'JR181', 'JR212',
       'JR224', 'JR260', 'JR266', 'JR269', 'JR275', 'JR311', 'JR321', 'JR325',
       'JR350', 'JR372', 'JR397', 'JR463', 'MK038', 'MK046', 'MK053', 'MK061',
       'MK145', 'MK178', 'MK215', 'MK225', 'MK238', 'NH047', 'NH071', 'NH099',
       'NH127', 'NH133', 'NH136', 'NH172', 'OB058', 'OB179', 'PA015', 'PA027',
       'PA033', 'PA064', 'PA116', 'RH019', 'RH023', 'RH029', 'RH065', 'RH119',
       'RH146', 'RH168', 'SF011'],
      dtype='object')

In [ ]:
id_labels = data.columns[1:]
# take the transpose since you want to see id on y-axis
id_matrix = np.array(data[id_labels].values, dtype=float).T
concert_dates = pd.to_datetime(data['concert_date'])
concert_dates = [d.date() for d in concert_dates]